services:
  postgres:
    image: postgres:16
    container_name: xupay_dns_postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_password
      POSTGRES_DB: xupay_dns_db
    ports:
      - "4510:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: